services:
  - type: web
    name: docsmart-backend
    env: node           # ✅ Tells Render this is a Node.js app
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y \
        build-essential \
        libcairo2-dev \
        libjpeg-dev \
        libpango1.0-dev \
        libgif-dev \
        librsvg2-dev \
        ghostscript \
        python3 \
        python3-pip \
        && pip3 install -r requirements.txt || true
      npm install
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
