services:
  - type: web
    name: docsmart-backend
    runtime: node
    buildCommand: |
      apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        libcairo2-dev \
        libjpeg-dev \
        libpango1.0-dev \
        libgif-dev \
        librsvg2-dev \
        ghostscript \
        python3 \
        python3-pip \
      && rm -rf /var/lib/apt/lists/*

      pip3 install --break-system-packages -r requirements.txt || true

      npm install
      npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
    region: oregon
    buildFilter:
      paths:
        - '**/*'
    pythonVersion: 3.10
