services:
  - type: web
    name: docsmart-backend
    env: node
    region: oregon  # or your preferred region
    buildCommand: |
      apt-get update && apt-get install -y \
        build-essential \
        libcairo2-dev \
        libjpeg-dev \
        libpango1.0-dev \
        libgif-dev \
        librsvg2-dev \
        ghostscript \
        python3 \
        python3-pip

      echo "✓ System packages installed."

      pip3 install --upgrade pip
      pip3 install -r requirements.txt
      echo "✓ Python packages installed."

      npm install
      echo "✓ Node packages installed."

      npm run build
    startCommand: npm start
    buildFilter:
      paths:
        - package.json
        - package-lock.json
        - requirements.txt
        - render.yaml
        - scripts/**
        - src/**
    autoDeploy: true
    branch: main
