services:
  - type: web
    name: docsmart-backend
    runtime: node
    buildCommand: |
      apt-get update && apt-get install -y \
        build-essential \
        libcairo2-dev \
        libjpeg-dev \
        libpango1.0-dev \
        libgif-dev \
        librsvg2-dev \
        ghostscript \
        python3 \
        python3-pip

      npm install
      pip3 install -r requirements.txt
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
